### ISSUE TITLE
Handle cases when youtube-dl throws an error

### ISSUE THREAD

**Issue by SimonGr3dal** [synox/youtube-dl-interactive#1]
The resolution selection dialogue doesn't work when `youtube-dl`  gives an error.

You should probably handle those cases by passing the error message along to the user.

<img width="981" alt="image" src="https://user-images.githubusercontent.com/6357979/58424081-e790ff80-8096-11e9-800d-4c546065f1b0.png">

**Comment by synox** [comment]
Thanks for sharing. The Video is: https://www.youtube.com/watch?v=gVEdQJ7qtJw

I will look into this.

**Comment by synox** [comment]
Please try again. 

    npm install -g youtube-dl-interactive
