### ISSUE TITLE
dep not found in npm repo

### ISSUE THREAD

**Issue by Monkey0803** [synox/youtube-dl-interactive#4]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/11564933/58457478-63538080-8159-11e9-869e-52f980e13448.png">
lib version too high

**Comment by synox** [comment]
Works for me, 2.0.0 is released https://github.com/sindresorhus/parse-columns/releases and https://www.npmjs.com/package/parse-columns

**Comment by synox** [comment]
Flush your caches and proxies...

**Comment by jinwyp** [comment]
Use the npm official registry instead of registry.npm.taobao.org. 

Delete  line below  in your .npmrc file

```
registry=https://registry.npm.taobao.org 
```
