### ISSUE TITLE
label:enhancement using standalone youtube-dl

### ISSUE THREAD

**Issue by bat-lab** [synox/youtube-dl-interactive#6]
I have stopped installing youtube-dl (from time to time it just stop working because of python related installation/update). I now using it as standalone executable which I invoke like the following:

```bash
some-path/youtube-dl ..
```

Will be nice if the user can specify where to find the standalone youtube-dl executable.

```bash
youtube-dl-interactive --youtube-dl-path "path-to-standalone-executable" URL
```
I think the change should be straightforward. And I  can implement the feature and submit a PR in this weekend.
Thank you for the work and let me know if you will be interested in this feature.

**Comment by synox** [comment]
You can put `some-path/youtube-dl` in your PATH, then it will find it. Does that work for you?
