### ISSUE TITLE
Mix 'video only' with audio, use JSON output

### ISSUE THREAD

**Issue by jinwyp** [synox/youtube-dl-interactive#7]
eg: https://www.youtube.com/watch?v=HLqIbhzrrls

After loading format , there are only 3 options : audio only / 640x360 / 1280x720 

And  this video  has '1920x1080' video only (no audio ) format

 { format: '137',
    code: '',
    extension: 'mp4',
    resolution: '1920x1080',
    note: '1080p 2447k , avc1.640028, 25fps, video only, 21.67MiB' },

I know that the video only format is exclude by code 

```
	remainingFormats = remainingFormats.filter(
		f => f.note.indexOf('video only') === -1
	)
```

So I want the '1920x1080' mp4 video and also with audio . 

It is easy to do with  command below 

```
youtube-dl  -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'  https://www.youtube.com/watch\?v\=HLqIbhzrrls 

```

youtube-dl  will  merge format video  '1920x1080'  and audio only m4a  format automatically.  but I cannot do that with youtube-dl-interactive.  

Suggestion :  Include video only format in the options  and merge video only format with best audio format .

**Comment by synox** [comment]
Oh that is great, I did not know that. 

Can the `-f` option you quoted also take a resolution specification? Often i want a medium quality video with best audio.

**Comment by jinwyp** [comment]
> Oh that is great, I did not know that.
> 
> Can the `-f` option you quoted also take a resolution specification? Often i want a medium quality video with best audio.

More info about youtube-dl " FORMAT SELECTION" pls check link below 

https://github.com/ytdl-org/youtube-dl#format-selection

**Comment by jinwyp** [comment]
There is another way to get video info to json 

use  --dump-json  and  --simulate (Do not download the video and do not write  anything to disk)

```
youtube-dl --simulate --dump-json  https://www.youtube.com/watch\?v\=HLqIbhzrrls 
```

**Comment by synox** [comment]
Thanks for the great input. This is now implemented in the current release.

**Comment by jinwyp** [comment]
cool!
