### ISSUE TITLE
Feature: add presets

### ISSUE THREAD

**Issue by synox** [synox/youtube-dl-interactive#8]
First question:

   ? Select presets or resolution:
    - Best audio + video 
    - Smallest file size
    - only audio
    - 480x240
    - 1024x720

**Comment by yura8** [comment]
Youtube-dl does presets, that's what they call flags and that's the opposite of what youtube-dl-interactive is trying to solve. If you need presets, just use upstream.

**Comment by synox** [comment]
@yura8 How should the UI of youtube-dl-interactive look / how should it work in your opinion?

**Comment by synox** [comment]
improved in current release, https://github.com/synox/youtube-dl-interactive/releases/tag/v0.1.0
