### ISSUE TITLE
can't install youtube-dl-interactive

### ISSUE THREAD

**Issue by GreenMelon** [synox/youtube-dl-interactive#9]
I have youtube-dl installed. And i use node@8.15.1. But some error appear when i install youtube-dl-interactive. It warns me that: 'No matching version found for parse-columns@^2.0.0'. But the latest version of 'parse-columns' is 2.0.0 in this address(https://www.npmjs.com/package/parse-columns). the dependencies in 'package.json' must be '"parse-columns": "2.0.0"' instead of '"parse-columns": "^2.0.0"'.

![image](https://user-images.githubusercontent.com/13148281/58535398-78dfad80-8220-11e9-9167-16a27cddadc2.png)
![image](https://user-images.githubusercontent.com/13148281/58535410-85640600-8220-11e9-8bcc-99b3cbe959c7.png)
![image](https://user-images.githubusercontent.com/13148281/58535423-8d23aa80-8220-11e9-96b9-253158723ffb.png)
![image](https://user-images.githubusercontent.com/13148281/58535442-9876d600-8220-11e9-9114-c46d1a5a5ef2.png)

**Comment by synox** [comment]
See #4, it seems you are using a repo with old versions.

**Comment by synox** [comment]
See #4, it seems you are using a repo with old versions.
